spring.application.name=flowytasks-api
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/flowytasks}
spring.datasource.username=${DB_USERNAME:flowytasks}
spring.datasource.password=${DB_PASSWORD:flowytasks}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
